#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Fhaculty\Graph\Graph as Graph;
use Relaxed\LCA\LowestCommonAncestor as LCA;

$graph = new Graph();


//Search.
$lca = new LCA($graph);
$vertices = $lca->generateVertices($graph,21);
$vertices['node_1']->createEdgeTo($vertices['node_2']);
$vertices['node_1']->createEdgeTo($vertices['node_3']);
$vertices['node_3']->createEdgeTo($vertices['node_8']);
$vertices['node_2']->createEdgeTo($vertices['node_4']);
$vertices['node_4']->createEdgeTo($vertices['node_5']);
$vertices['node_4']->createEdgeTo($vertices['node_6']);
$vertices['node_4']->createEdgeTo($vertices['node_7']);
$vertices['node_5']->createEdgeTo($vertices['node_11']);
$vertices['node_5']->createEdgeTo($vertices['node_12']);
$vertices['node_6']->createEdgeTo($vertices['node_13']);
$vertices['node_7']->createEdgeTo($vertices['node_16']);
$vertices['node_8']->createEdgeTo($vertices['node_9']);
$vertices['node_8']->createEdgeTo($vertices['node_10']);
$vertices['node_9']->createEdgeTo($vertices['node_17']);
$vertices['node_10']->createEdgeTo($vertices['node_18']);
$vertices['node_12']->createEdgeTo($vertices['node_14']);
$vertices['node_12']->createEdgeTo($vertices['node_15']);
$vertices['node_17']->createEdgeTo($vertices['node_19']);
$vertices['node_17']->createEdgeTo($vertices['node_20']);
$vertices['node_18']->createEdgeTo($vertices['node_21']);
$ancestor = $lca->find($vertices['node_14'], $vertices['node_15']);